name: CI

on:
  push:
    branches: [ Developpement ]
  pull_request:
    branches: [ Developpement ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.4.3
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: da50
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Create user and grant privileges
      - name: Create MySQL user
        run: |
          sleep 30
          docker exec ${{ job.services.mysql.id }} mysql -u root -proot -e "CREATE USER 'hibernate_user'@'%' IDENTIFIED BY 'root';"
          docker exec ${{ job.services.mysql.id }} mysql -u root -proot -e "GRANT ALL PRIVILEGES ON da50.* TO 'hibernate_user'@'%';"

      # Execute the tests specifying connection informations to DB
      - name: Build with Maven
        run: |
          mvn -B install --file pom.xml \
          -Dhibernate.connection.url="jdbc:mysql://mysql:3306/da50" \
          -Dhibernate.connection.username="hibernate_user" \
          -Dhibernate.connection.password="root"

      - name: Upload Surefire reports
        uses: actions/upload-artifact@v3
        with:
          name: surefire-reports
          path: target/surefire-reports