name: CI

on:
  push:
    branches: [ Developpement, DEV_database ]
  pull_request:
    branches: [ Developpement, DEV_database ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Start Docker container
      - name: Start MySQL
        run: docker run -d --name mysql -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=da50 -p 3306:3306 mysql:8.4.3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Execute the tests specifying connection informations to DB
      - name: Build with Maven
        run: mvn -B install --file pom.xml -Ddb.url="jdbc:mysql://localhost:3306/da50" -Ddb.user="hibernate_user" -Ddb.password="root"

      - name: Upload Surefire reports
        uses: actions/upload-artifact@v3
        with:
          name: surefire-reports
          path: target/surefire-reports

      # Stop Docker container
      - name: Stop MySQL
        run: docker stop mysql
